# Generated by Django 3.0.7 on 2022-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minamount',
        ),
    ]
