# Generated by Django 3.0.7 on 2022-01-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_minamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Type', 'Type'), ('Order', 'Order'), ('Type-Order', 'Type-Order')], default='None', max_length=10),
        ),
    ]
