# Generated by Django 3.0.7 on 2022-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220114_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
